---
- name: Azure Webserver Compute Configuration
  hosts: tag_Ansible_webserver
  become: yes

  tasks:
  - name: Install Software
    ansible.builtin.package:
      name:
        - git
        - apache2
      state: latest
      update_cache: yes
    become: yes

  - name: Enable and start apache2
    systemd:
      name: apache2
      state: started
      enabled: yes
