---
- name: Azure Webserver Infrastructure - Network
  hosts: localhost
  vars:

  tasks:
  - name: create Resource Group
    azure_rm_resourcegroup:
      name: "{{ resourcegroup }}"
      location: "{{ location }}"

  - name: Create a virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resourcegroup }}"
      name: "{{ virtualnetwork_name }}"
      address_prefixes_cidr:
          - "{{ cidr }}"

  - name: Create a subnet
    azure_rm_subnet:
      resource_group: "{{ resourcegroup }}"
      virtual_network_name: "{{ virtualnetwork_name }}"
      name: "{{ webserver_subnet }}"
      address_prefix_cidr: "{{ cidr_public_a }}"
