name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run network playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: network.yml
        # Optional, directory where playbooks live
        directory: ./

    - name: Run security playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: security.yml
        # Optional, directory where playbooks live
        directory: ./