name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run network playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: network.yml
        directory: ./

    - name: Run security playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: security.yml
        directory: ./

    - name: Run compute playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: compute.yml
        directory: ./

    - name: Run loadbalancer playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: loadbalancer.yml
        directory: ./

    - name: Run install compute playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: install_compute.yml
        directory: ./
        key: ~/.ssh/webserver
        options:
          --inventory inv.azure_rm.yml
          --extra-vars "ansible_user=azureuser"